Adaptiv
slavaider/task-manager pull request #35
Opened 2022-05-17 11:51 UTC by anna-left

2022-05-17 12:20 UTC, slavaider requested changes

2022-05-17 12:20 UTC, slavaider commented on src/app/task-manager/components/header/header.component.scss
> +    padding-top: 1vh;
???

2022-05-17 12:20 UTC, slavaider commented on src/app/task-manager/components/header/header.component.scss
> +    height: 92vh;
???

2022-05-17 12:20 UTC, slavaider commented on src/app/task-manager/pages/board-page/board-page.component.scss
> +  // top: 7vh; // 7 - header
...

2022-05-17 12:20 UTC, slavaider commented on src/app/task-manager/pages/welcome/welcome.component.scss
> +  min-height: 87vh;
min-height:100% ?

2022-05-17 12:20 UTC, slavaider commented on src/app/task-manager/pages/welcome/welcome.component.scss
> +    font-size: 3.5rem !important;
Не используй important без надобности, просто усиль специфичность, например добавив ещё один класс для элемента

2022-05-17 12:20 UTC, slavaider commented on src/app/task-manager/pages/welcome/welcome.component.scss
> +    font-size: 3rem !important;
+1

2022-05-17 12:20 UTC, slavaider commented on src/app/task-manager/pages/welcome/welcome.component.scss
> +    font-size: 2.5rem !important;
+1

2022-05-17 12:20 UTC, slavaider commented on src/app/task-manager/pages/welcome/welcome.component.scss
> +    font-size: 2.5rem !important;
+

2022-05-18 08:08 UTC, slavaider approved these changes

2022-05-18 11:17 UTC, VitaliSantalau approved these changes

2022-05-18 11:29 UTC, merged